server:
  port: 8090
spring:
  application:
    name: sellergoods-services
  profiles:
    active: dev
    include: dao
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss              #日期格式化
    serialization:
      indent_output: true                         #格式化输出
      fail_on_empty_beans: false                  #忽略无法转换的对象
    default-property-inclusion: always            #设置空如何序列化
    deserialization:
      fail_on_unknown_properties: false           #允许对象忽略json中不存在的属性
    parser:
      allow_unquoted_control_chars: true          #允许出现特殊字符和转义符
      allow_single_quotes: true                   #允许出现单引号
    time-zone: GMT+8                              #配置时区
log:
  path: E:/java/logs/pinyougou/sellergoods-services